name: HACS Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7

      - name: HACS Action
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a  # v22.5.0
        with:
          category: "integration"
