name: HACS Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@22.5.0
        with:
          category: "integration"
          ignore: "brands"
