name: Validate with hassfest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    name: Validate with hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master