name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  auto-update:
    name: Pre-commit auto-update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip

      - name: Install uv
        run: pip install uv

      - name: Install pre-commit
        run: uv pip install --system pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
          body: |
            Update versions of tools in pre-commit
            configs to latest version
          labels: dependencies
