name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    name: Release Drafter
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@5a60cd8ddda6dc14fce77159675b8fd2cdca4007  # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
