name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test with tox
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
          cache: pip

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install --system tox tox-uv

      - name: Test with tox
        run: tox
