name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test with tox
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5.4.0
        with:
          enable-cache: true
          python-version: 3.13

      - name: Install dependencies
        run: uv pip install tox tox-uv

      - name: Test with tox
        run: tox
